# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.3 on 2017-07-25 23:07
=======
# Generated by Django 1.10 on 2017-07-25 21:38
>>>>>>> 69f3f97ce81135b949b11af1315cb5bd41293ae3
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_level', models.IntegerField()),
            ],
        ),
    ]
