# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
