# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingCart', to='users_app.User'),
        ),
    ]
