# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0003_auto_20170726_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total',
        ),
    ]
