# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0005_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billingInfo', to='orders_app.Order'),
        ),
    ]
